sudo: required

services:
  - docker

branches:
  only:
    - master

before_script:
  - docker login -u=${DOCKER_USER} -p=${DOCKER_PASS}

script:
  - docker build -t base .
  - docker tag base agavelab/golang-base:${TRAVIS_BRANCH}
  - docker tag base agavelab/golang-base:${TRAVIS_BUILD_ID}
  - docker tag base agavelab/golang-base
  - docker push agavelab/golang-base:${TRAVIS_BRANCH}
  - docker push agavelab/golang-base:${TRAVIS_BUILD_ID}
  - docker push agavelab/golang-base
